#!/usr/bin/env python2.7
"""
creare un file di configurazione ScarcellaBot_config
nel quale definire le seguenti variabili

TELEGRAM_BOT_TOKEN
TELEGRAM_USER_ID
IMAGES_PATH
TELEGRAM_USERS_ID
"""
import sys
import telepot
import time
import ScarcellaBot_config
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
from pprint import pprint

class MyHandler(FileSystemEventHandler):
    # def on_any_event(self, event):
        # print "Evento: " + event.event_type
    def on_created(self, event):
        print "Nuovo file: " + event.src_path
        # bot.sendMessage(ScarcellaBot_config.TELEGRAM_USER_ID, 'Nuovo file: ' + event.src_path)
        f = open(event.src_path, 'rb')
        bot.sendPhoto(ScarcellaBot_config.TELEGRAM_USER_ID, f)

if __name__ == "__main__":
    # ------ TELEGRAM --------------
    # imposto il telegram Bot
    try:
        bot=telepot.Bot(ScarcellaBot_config.TELEGRAM_BOT_TOKEN)
        utente = bot.getMe()
        # scambio qualche messaggio all'avvio:
        print(utente)
    except:
        print "Impossibile inizializzare il BOT", sys.exc_info()[0]
    for u in ScarcellaBot_config.TELEGRAM_USERS_ID:
        print u # stampo il destinatario
        bot.sendMessage(ScarcellaBot_config.TELEGRAM_USERS_ID, 'Mi sono avviato adesso! - ' + str(datetime.now()))
    # definisco il gestore che deve essere invocato nel loop del bot
    def handle(msg):
        pprint(msg)
    # avvio il loop del bot che resta in ascolto dei messaggi
    # verso il BPT (passando il mio gestore)
    bot.message_loop(handle)
    
    # ------ WATCHDOG --------------
    # watchdog folder
    path = ScarcellaBot_config.IMAGES_PATH if ScarcellaBot_config.IMAGES_PATH > 1 else '.'
    event_handler = MyHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=False)
    observer.start()

    # tengo in vita il processo fino a che
    # qualcuno non lo interrompe da tastiera
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
